name: Build with maven

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
         java-version: '8'
         distribution: 'temurin'
         cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests 
      - name: Docker login
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     # - name: Get current date
      #  id: date
       # run: echo "::set-output name=date::$(date +'%Y-%m-%d')"  
        
      - name: Set MY_DATE
        run: echo "MY_DATE=date +'%Y-%m-%d-%H.%M'"
      - name: Test MY_DATE 
        run: echo ${{ env.MY_DATE }}  
      - name: Build image
        run: cp -R docker target/ && cp target/*.jar docker/
      - name: Build docker image
        run: docker build . --file docker/Dockerfile -t bookappointment:latest   
      - name: Push the image to nexus repo
        run: |
         docker login -u admin -p ${{ secrets.NEXUS_PASSWORD }} http://13.232.182.52:8083
         docker tag bookappointment:latest 13.232.182.52:8083/java-maven-project/bookappointment:v1
         docker push 13.232.182.52:8083/java-maven-project/bookappointment:v1
        
     # - name: Docker push
    #  run: docker push ${{ secrets.DOCKER_USER }}/bookappointment:latest
      
    #- name: Build & push Docker image
     # uses: mr-smithers-excellent/docker-build-push@v5
      #with:
       #image: chandu7781/bookappointment
       #tags: latest
       #registry: docker.io
       #dockerfile: docker/Dockerfile
       #username: ${{ secrets.DOCKER_USERNAME }}
       #password: ${{ secrets.DOCKER_PASSWORD }}     
