name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests  
    - name: Build image
      run: cp -R docker target/ && cp target/*.jar docker/
      
   # - uses: docker/login-action@v2
    #  name: Docker login 
     # env:
      # DOCKER_USER: ${{ secrets.DOCKER_USER }}
       #DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build docker image
      run: docker build . --file docker/Dockerfile -t bookappointment:latest 
     
    - name: Push the image to nexus repo
      run: |
       docker login -u admin -p ${{ secrets.NEXUS_PASSWORD }} http://3.110.151.212:8083
       docker tag bookappointment:latest 3.110.151.212:8083/java-maven-project/bookappointment:v1
       docker push 3.110.151.212:8083/java-maven-project/bookappointment:v1
    
   # - name: Docker push
    #  run: docker push ${{ secrets.DOCKER_USER }}/bookappointment:latest
      
    #- name: Build & push Docker image
     # uses: mr-smithers-excellent/docker-build-push@v5
      #with:
       #image: chandu7781/bookappointment
       #tags: latest
       #registry: docker.io
       #dockerfile: docker/Dockerfile
       #username: ${{ secrets.DOCKER_USERNAME }}
       #password: ${{ secrets.DOCKER_PASSWORD }}     
